version: '3.9'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # ports:
    #   - "3000:3000"
    volumes:
      - .:/node_app/app
    command: /bin/sh -c "chmod +x entrypoint.sh && chmod +x healthcheck.sh && /node_app/app/entrypoint.sh"
    env_file:
      - .env
    restart: always
    # healthcheck:
    #   test: ./healthcheck.sh
    #   interval: 5s
    #   timeout: 5s
    #   retries: 1
    #   start_period: 10s

  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
